FROM ubuntu:24.04

RUN apt-get update && \
  apt-get install -y openssh-server sudo build-essential git curl vim && \
  mkdir /var/run/sshd && \
  curl -fsSL https://code-server.dev/install.sh | sh && \
  echo 'root:rootpassword' | chpasswd && \
  useradd -m -s /bin/bash sam && \
  echo 'sam:sampassword' | chpasswd && \
  sed -i 's/^#\?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
  sed -i 's/^#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config

ENV PASSWORD=mysecretpassword

RUN curl -fsSL https://code-server.dev/install.sh | sh

EXPOSE 22 8080

CMD ["/usr/sbin/sshd", "-D"]

