---
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mongodb
    ports:
      - "27017-27019:27017-27019"
    networks:
      - backend
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - jaeger-data:/tmp
    networks:
      - backend
    restart: unless-stopped
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    user: "0:0" # Run as root to avoid permission issues
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3100:3100" # tempo
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
      - "9095:9095" # tempo grpc
      - "9411:9411" # zipkin
    networks:
      - backend
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3456:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - backend
    depends_on:
      - tempo
    restart: unless-stopped
networks:
  backend:
    driver: bridge
  postgres:
    driver: bridge
volumes:
  postgres:
  jaeger-data:
  tempo-data:
  grafana-data:
