---
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mongodb
    ports:
      - "27017-27019:27017-27019"
    networks:
      - backend
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - jaeger-data:/tmp
    networks:
      - backend
    restart: unless-stopped
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    user: "0:0" # Run as root to avoid permission issues
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3100:3100" # tempo
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
      - "9095:9095" # tempo grpc
      - "9411:9411" # zipkin
    networks:
      - backend
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3456:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - backend
    depends_on:
      - tempo
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "8999:9000"
    networks:
      - backend
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3069:8080"
    volumes:
      - open-webui:/app/backend/data
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    restart: always
    depends_on:
      - ollama
    networks:
      - ai
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - ai
  ollama-local:
    image: ollama/ollama
    container_name: ollama-local
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - ai
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.deno-jupyter
    ports:
      - "8888:8888"
    volumes:
      - /media/sam/main/notebooks:/home/jovyan/work
    environment:
      GRANT_SUDO: yes
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_PASSWORD: "assword"
    working_dir: /home/jovyan/work
    user: jovyan
  ubuntu-ssh:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu-dev
    ports:
      - "2222:22"
    restart: unless-stopped
    networks:
      - backend
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - /media/sam/main/chroma:/chroma/db
    restart: unless-stopped
    networks:
      - ai
  mcp-time:
    build:
      context: .
      dockerfile: Dockerfile.mcp-time
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
networks:
  ai:
    driver: bridge
  backend:
    driver: bridge
  postgres:
    driver: bridge
volumes:
  postgres:
  jaeger-data:
  tempo-data:
  grafana-data:
  portainer-data:
  open-webui:
  ollama_data:
  chromadb:
